name: BLANkTEST
on:
  workflow_dispatch:
jobs:
  build:
    continue-on-error: true
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest]
    steps:     
     - name: Run a one-line script
       run: echo Hello, world!
